# Generated by Django 5.2.17 on 2026-10-05 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('sql', models.TextField(help_text='One SELECT/WITH statement. Use :doctor_id to scope rows for doctors.')),
                ('chart_type', models.CharField(choices=[('TABLE', 'Table'), ('NUMBER', 'Number (KPI)'), ('BAR', 'Bar'), ('STACKED_BAR', 'Stacked bar'), ('HBAR', 'Horizontal bar'), ('LINE', 'Line'), ('AREA', 'Area'), ('PIE', 'Donut'), ('SCATTER', 'Scatter')], default='BAR', max_length=12)),
                ('x_column', models.CharField(blank=True, help_text='Category / date column (default: first column)', max_length=100)),
                ('y_columns', models.CharField(blank=True, help_text='Comma-separated value columns (default: second column)', max_length=300)),
                ('series_column', models.CharField(blank=True, help_text='Optional column that splits the data into series', max_length=100)),
                ('doctor_access', models.BooleanField(default=False, help_text='Visible to doctors, filtered by :doctor_id')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
