# Generated by Django 5.2.17 on 2026-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.CharField(choices=[('POSTGRES', 'PostgreSQL'), ('CLICKHOUSE', 'ClickHouse (high performance)')], default='POSTGRES', max_length=12),
        ),
    ]
